variant:
 - single-binary
 - onedir
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [linux]
  - "2.28"                     # [linux]
