{% set conda_version = "23.11.0" %}
{% set conda_libmamba_solver_version = "23.11.1" %}
{% set libmambapy_version = "1.5.5" %}
{% set constructor_version = "3.5.0" %}
{% set python_version = "3.9.15" %}
{% set pyver = "".join(python_version.split(".")[:2]) %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../
  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 273d49db8ea723426b87866381daf2df27c7bca2c3474196460d637b62de2a1c
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - ../src/conda_patches/0003-Return-unknown-module-in-deprecations.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 787ffd85e9414bdf70fe531f01eab3987a040e3f6a6ac3a01409f4d332f7de9e  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  string: "g{{ GIT_FULL_HASH[:7] }}_py{{ pyver }}_{{ PKG_BUILDNUM }}"
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=1.6
    - menuinst >=2.0.1
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
