{% set conda_version = "23.5.0" %}
{% set constructor_version = "3.4.3" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../
  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 57155b96dd94ba95e421b4c36695dbf6972bcfb9b5e41ee0674bb796b8386f58
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 4a1f5ae2ba74175cc5d0770d6d43147253091f8869fa20568a02d5ddb7963dee  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=1.6
    - menuinst >=1.4.18  # [win]
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  commands:
    - export CONDA_SOLVER="classic"  # [unix]
    - ${PREFIX}/standalone_conda/conda.exe -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm    # [unix]
    - set "CONDA_SOLVER=classic"  # [win]
    - '%PREFIX%\standalone_conda\conda.exe -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe create -y -p env_test zlib tqdm'    # [win]

about:
  home: https://github.com/conda/conda-standalone
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
