{% set conda_version = "24.4.0" %}
{% set conda_libmamba_solver_version = "24.1.0" %}
{% set libmambapy_version = "1.5.8" %}
{% set constructor_version = "3.7.0" %}
{% set python_version = "3.11.9" %}
{% set pyver = "".join(python_version.split(".")[:2]) %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../

  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 6e0f3fb26a39f27c3c8fb1baf76ab85010b552e39ed145b4a3a2795ad344105d
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: e84de1d7db3dbd394c03fa0e966bd293729307b9de0c8733ed7189f422a4b5b5  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  string: "g{{ GIT_FULL_HASH[:7] }}_py{{ pyver }}_{{ PKG_BUILDNUM }}"
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=1.6
    - conda-package-streaming >=0.9.0
    - menuinst >=2.0.2
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
    - menuinst >=2.0.2
  source_files:
    - tests
  commands:
    - pytest -vv
    - test ! -e {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
