{% set conda_version = "25.9.1" %}
{% set conda_libmamba_solver_version = "25.4.0" %}
{% set libmambapy_version = "2.0.5" %}
{% set constructor_lower_bound = "3.12.1" %}
{% set menuinst_lower_bound = "2.4.0" %}
{% set python_version = "3.13.7" %}
{% set pyver = "".join(python_version.split(".")[:2]) %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../

  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: a8fd4efd493203fc8017f9d80d2d69fbc97a6f583f3da956097eaaf160e84f99
    folder: conda_src
    # NOTE: All files affected by a patch need to be manually copied
    # from src to PREFIX in build.sh and bld.bat
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - ../src/conda_patches/0003-Restrict-search-paths.patch
      - ../src/conda_patches/0004-Fix-conda-run.patch

build:
  number: 0
  string: "g{{ GIT_FULL_HASH[:7] }}_py{{ pyver }}_single_{{ PKG_BUILDNUM }}"  # [variant != 'onedir']
  string: "g{{ GIT_FULL_HASH[:7] }}_py{{ pyver }}_onedir_{{ PKG_BUILDNUM }}"  # [variant == 'onedir']
  detect_binary_files_with_prefix: False  # [variant == 'onedir']
  track_features:
    - conda-standalone_onedir  # [variant == 'onedir']
  ignore_run_exports:
    - '*'
  missing_dso_whitelist:          # [osx and variant == 'onedir']
    - "$RPATH/libswift*.dylib"    # [osx and variant == 'onedir']
  rpaths:                         # [linux and variant == 'onedir']
    - standalone_conda/_internal  # [linux and variant == 'onedir']
  overlinking_ignore_patterns:   # [win and variant == 'onedir']
    - '*'                        # [win and variant == 'onedir']
  script_env:
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}
    - PYINSTALLER_BUILD_VARIANT={{ variant }}

requirements:
  build:
    - {{ stdlib('c') }}
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.12.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_lower_bound }}

test:
  requires:
    - conda
    - menuinst >={{ menuinst_lower_bound }}
    - pytest
    - ruamel.yaml
  source_files:
    - tests
  commands:
    - pytest -vv
    - test ! -e {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
  description: A standalone conda executable built with PyInstaller.
  license: LicenseRef-CondaStandalone
  license_family: Other
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  doc_url: https://github.com/conda/conda-standalone
  dev_url: https://github.com/conda/conda-standalone
