{% set conda_version = "24.11.0" %}
{% set conda_libmamba_solver_version = "24.9.0" %}
{% set libmambapy_version = "1.5.11" %}
{% set constructor_version = "3.10.0" %}
{% set menuinst_lower_bound = "2.2.0" %}
{% set python_version = "3.12.7" %}
{% set pyver = "".join(python_version.split(".")[:2]) %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../

  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 9ae1433949ca80eddfd81f0d5bd9eb8c291c7e101cbb440f8bdba324c9ea470c
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - ../src/conda_patches/0003-Restrict-search-paths.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: cfb77a5e64b5b2b44fdb5c3d04adbb652c1249a86ea2e88f9b293e367a809caf  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  string: "g{{ GIT_FULL_HASH[:7] }}_py{{ pyver }}_{{ PKG_BUILDNUM }}"
  ignore_run_exports:
    - '*'
  script_env:
    - PYINSTALLER_CONDARC_DIR={{ RECIPE_DIR }}

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=2.3.0
    - conda-package-streaming >=0.9.0
    - menuinst >={{ menuinst_lower_bound }}
    - conda-libmamba-solver ={{ conda_libmamba_solver_version }}
    - libmambapy ={{ libmambapy_version }}
    - archspec >=0.2.3
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - conda
    - menuinst >={{ menuinst_lower_bound }}
    - pytest
    - ruamel.yaml
  source_files:
    - tests
  commands:
    - pytest -vv
    - test ! -e {{ PREFIX }}/bin/codesign  # [osx]

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
