{% set conda_version = "22.11.1" %}
{% set constructor_version = "3.3.1" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../
  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: f9256a7e71a9f35063b683f6c7823acf05c1f75468fc609954f1f5efae7c03ac
    folder: conda_src
    patches:
      - src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: b000dde0ac8641c92f7342362173968505d4e85845be37655b5b9221cb65f3a8  # [win]
    folder: constructor  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=1.6
    - menuinst >=1.4.18  # [win]
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  commands:
    - export CONDA_SOLVER="classic"  # [unix]
    - ${PREFIX}/standalone_conda/conda.exe -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe create -y -p ./env_test zlib tqdm    # [unix]
    - set "CONDA_SOLVER=classic"  # [win]
    - '%PREFIX%\standalone_conda\conda.exe -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe create -y -p env_test zlib tqdm'    # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
