{% set conda_version = "23.7.2" %}
{% set constructor_version = "3.4.5" %}
{% set python_version = "3.9.15" %}

package:
  name: conda-standalone
  version: {{ conda_version }}

source:
  - path: ../
  - url: https://github.com/conda/conda/archive/{{ conda_version }}.tar.gz
    sha256: 4fd44862ef87c73e4641b0c40a0873e103a097d6fd4a992041cfa9177ce20ac8
    folder: conda_src
    patches:
      - ../src/conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - ../src/conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - ../src/conda_patches/0003-Return-unknown-module-in-deprecations.patch

  - url: https://github.com/conda/constructor/archive/{{ constructor_version }}.tar.gz  # [win]
    sha256: 425a7b6825a3dba21c21d9234ff1ceac8efea6ebc14e2b0e80d0880f502b3e01  # [win]
    folder: constructor_src  # [win]

build:
  number: 0
  ignore_run_exports:
    - '*'

requirements:
  build:
    - pyinstaller
    - python ={{ python_version }}
    - conda ={{ conda_version }}
    - conda-package-handling >=1.6
    - menuinst >=1.4.18,<2.0a0  # [win]
  run_constrained:
    - constructor >={{ constructor_version }}

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv

about:
  home: https://github.com/conda/conda-standalone
  license: LicenseRef-CondaStandalone
  license_file:
    - LICENSE
    - 3rd-party-licenses.json
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.
